package rules

import com.nexos.demo.models.dto.DetalleFacturaDTO;
import java.math.BigDecimal;

global org.slf4j.Logger logger;

dialect "java"

rule "Regla de descuento - compra sin descuento"
    when
        $detail: DetalleFacturaDTO(importe.compareTo(new BigDecimal(50000)) == -1 || importe.compareTo(new BigDecimal(50000)) == 0)
    then
        $detail.setDescuento("0.0");
        logger.info("No se aplica descuento para el objeto " + $detail);
end

rule "Regla de descuento - compra con descuento del 5%"
    when
        $detail: DetalleFacturaDTO(importe.compareTo(new BigDecimal(50000)) == 1 && importe.compareTo(new BigDecimal(100000)) == -1)
    then
        $detail.setDescuento("0.05");
        $detail.aplicarDescuento();
        logger.info("Aplicando descuento del 5% al objeto " + $detail);
end

rule "Regla de descuento - compra con descuento del 10%"
    when
        $detail: DetalleFacturaDTO(importe.compareTo(new BigDecimal(100000)) == 1 || importe.compareTo(new BigDecimal(100000)) == 0)
    then
        $detail.setDescuento("0.1");
        $detail.aplicarDescuento();
        logger.info("Se aplica descuento del 10% para el objeto " + $detail);
end